### ISSUE TITLE
SetupDummyData error

### ISSUE THREAD

**Issue by WittevrongelLaura** [WittevrongelLaura/BackendDev-project#1]
400 Bad Request
{
  "error": "Serialization and deserialization of 'System.Action' instances are not supported. Path: $.MoveNextAction."
}

When executing "GET http://localhost:3000/setup"

**Comment by nathansegers** [comment]
Je zal de _nursingService.GetAllAsync() nog moeten `await`-en.
Momenteel ben je een System.Action aan het terugsturen, in plaats van een List, omdat die asynchroon is.
